# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AutoIdentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7', :inhibit_warnings => true
  pod 'AlamofireLogger'
  pod 'Starscream', '~> 3.0.2'
  pod 'SwiftMsgPack', '~> 1.0.0'
  pod 'OpenCV2', '~> 3.4.1'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'
  pod 'lottie-ios'

  # Pods for AutoIdentApp

end
